import type { Department } from "./types";

export const departmentsMock: Department[] = [
  {
    id: "icu",
    name: "Unitate Terapie Intensiva",
    type: "Ingrijire critica",
    unit: "ATI - Turn B",
    lead: "Dr. Reyes",
    staff: 84,
    currentRisk: 78,
    predictedRisk: 86,
    staffPressureIndex: 82,
    interventionUrgency: 88,
    fatigueIndex: 71,
    shortageRisk: 64,
    occupancy: 94,
    trend: "up",
    delta: 6.4,
  },
  {
    id: "er",
    name: "Departament Urgente",
    type: "Urgente",
    unit: "UPU - Parter",
    lead: "Dr. Okafor",
    staff: 112,
    currentRisk: 71,
    predictedRisk: 79,
    staffPressureIndex: 88,
    interventionUrgency: 81,
    fatigueIndex: 68,
    shortageRisk: 58,
    occupancy: 97,
    trend: "up",
    delta: 4.1,
  },
  {
    id: "onc",
    name: "Oncologie",
    type: "Specialitate",
    unit: "Turn A - L4",
    lead: "Dr. Lindqvist",
    staff: 56,
    currentRisk: 62,
    predictedRisk: 66,
    staffPressureIndex: 64,
    interventionUrgency: 60,
    fatigueIndex: 59,
    shortageRisk: 41,
    occupancy: 81,
    trend: "stable",
    delta: 0.6,
  },
  {
    id: "ped",
    name: "Pediatrie",
    type: "Specialitate",
    unit: "Turn C - L2",
    lead: "Dr. Haddad",
    staff: 64,
    currentRisk: 44,
    predictedRisk: 49,
    staffPressureIndex: 48,
    interventionUrgency: 42,
    fatigueIndex: 41,
    shortageRisk: 30,
    occupancy: 72,
    trend: "down",
    delta: -2.8,
  },
  {
    id: "sur",
    name: "Chirurgie",
    type: "Chirurgical",
    unit: "Turn A - L3",
    lead: "Dr. Brennan",
    staff: 78,
    currentRisk: 58,
    predictedRisk: 64,
    staffPressureIndex: 72,
    interventionUrgency: 63,
    fatigueIndex: 55,
    shortageRisk: 47,
    occupancy: 86,
    trend: "up",
    delta: 3.2,
  },
  {
    id: "mat",
    name: "Maternitate",
    type: "Specialitate",
    unit: "Turn C - L1",
    lead: "Dr. Kovac",
    staff: 48,
    currentRisk: 39,
    predictedRisk: 42,
    staffPressureIndex: 44,
    interventionUrgency: 35,
    fatigueIndex: 36,
    shortageRisk: 22,
    occupancy: 68,
    trend: "down",
    delta: -1.4,
  },
  {
    id: "rad",
    name: "Radiologie",
    type: "Diagnostic",
    unit: "Turn B - L1",
    lead: "Dr. Park",
    staff: 32,
    currentRisk: 51,
    predictedRisk: 55,
    staffPressureIndex: 58,
    interventionUrgency: 49,
    fatigueIndex: 47,
    shortageRisk: 34,
    occupancy: 74,
    trend: "stable",
    delta: 0.9,
  },
  {
    id: "psy",
    name: "Psihiatrie",
    type: "Sanatate comportamentala",
    unit: "Turn D - L2",
    lead: "Dr. Almeida",
    staff: 38,
    currentRisk: 66,
    predictedRisk: 72,
    staffPressureIndex: 60,
    interventionUrgency: 70,
    fatigueIndex: 61,
    shortageRisk: 52,
    occupancy: 79,
    trend: "up",
    delta: 5.0,
  },
];
