import type { Scenario } from "./types";
import { buildTimeSeries } from "./timeseries";
import { buildForecastOutput } from "./forecast";

export const scenariosMock: Scenario[] = [
  {
    id: "icu-night",
    name: "ICU Night Shift Overload",
    department: "Intensive Care · Tower B",
    riskLevel: "critical",
    risk: 82,
    description: "Sustained overtime and elevated patient-to-nurse ratio across 14 consecutive nights.",
    drivers: ["Consecutive night shifts", "Overtime > 12h/week", "Patient ratio 5.4:1"],
    recommendedAction: "Add 2 floating nurses to ICU night rotation for 7 days and cap overtime at 8h/week.",
    mockInputSeries: buildTimeSeries(30),
    mockForecastSeries: buildForecastOutput(30, 14),
    spark: [42, 48, 51, 55, 60, 64, 68, 71, 73, 76, 79, 82],
  },
  {
    id: "er-surge",
    name: "Departament Urgente Surge",
    department: "ER · Ground floor",
    riskLevel: "elevated",
    risk: 76,
    description: "Walk-in volume +34% during weekend; triage bottleneck between 22:00–04:00.",
    drivers: ["Weekend walk-in volume +34%", "Triage staffing gap 22:00–04:00", "Overtime trending up"],
    recommendedAction: "Activate weekend surge protocol and reassign 2 triage nurses from urgent care.",
    mockInputSeries: buildTimeSeries(30),
    mockForecastSeries: buildForecastOutput(30, 14),
    spark: [52, 55, 58, 62, 60, 65, 70, 72, 74, 73, 75, 76],
  },
  {
    id: "sur-short",
    name: "Sectie Chirurgie Staff Deficit",
    department: "Surgery · Tower A",
    riskLevel: "elevated",
    risk: 68,
    description: "3 scheduled OR teams understaffed by 1 scrub nurse each for 6 days.",
    drivers: ["Scrub nurse vacancy", "Elective backlog", "Cross-cover fatigue"],
    recommendedAction: "Reassign 3 scrub nurses from float pool and defer 2 elective procedures.",
    mockInputSeries: buildTimeSeries(30),
    mockForecastSeries: buildForecastOutput(30, 14),
    spark: [40, 44, 46, 48, 52, 55, 58, 60, 63, 65, 67, 68],
  },
  {
    id: "ped-seasonal",
    name: "Pediatric Unit Seasonal Pressure",
    department: "Pediatrie · Tower C",
    riskLevel: "moderate",
    risk: 54,
    description: "RSV admissions trending up; predicted +20% beds in the next 10 days.",
    drivers: ["RSV admissions +18%", "Seasonal peak forecast", "Reduced bed turnover"],
    recommendedAction: "Open 6 additional pediatric beds and pre-stage respiratory therapy team.",
    mockInputSeries: buildTimeSeries(30),
    mockForecastSeries: buildForecastOutput(30, 14),
    spark: [30, 33, 36, 40, 42, 44, 47, 49, 50, 52, 53, 54],
  },
  {
    id: "onc-load",
    name: "Oncologie Department Emotional Load",
    department: "Oncologie · Tower A L4",
    riskLevel: "elevated",
    risk: 62,
    description: "Stress survey scores rose +0.9 points; 4 staff flagged for wellbeing check.",
    drivers: ["Stress survey delta +0.9", "Bereavement events", "Long-tenure fatigue"],
    recommendedAction: "Schedule 30-min wellbeing check-ins and bring in counselling support for 2 weeks.",
    mockInputSeries: buildTimeSeries(30),
    mockForecastSeries: buildForecastOutput(30, 14),
    spark: [44, 46, 48, 50, 51, 53, 55, 57, 58, 60, 61, 62],
  },
  {
    id: "weekend",
    name: "Weekend Understaffing Scenario",
    department: "All wards · Sat–Sun",
    riskLevel: "elevated",
    risk: 71,
    description: "Routine weekend coverage gap intersects with elective surgery backlog.",
    drivers: ["Weekend baseline coverage gap", "Elective backlog", "Sick-leave drift"],
    recommendedAction: "Activate weekend float pool and shift 2 elective cases to Monday.",
    mockInputSeries: buildTimeSeries(30),
    mockForecastSeries: buildForecastOutput(30, 14),
    spark: [38, 42, 46, 50, 54, 58, 62, 65, 67, 68, 70, 71],
  },
];
