apiVersion: v1
kind: ServiceAccount
metadata:
  name: telemetry-generator
  namespace: pulseguard
  annotations:
    iam.gke.io/gcp-service-account: pulseguard-telemetry@project-73d1e32a-8e68-4750-93c.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: realtime-gateway
  namespace: pulseguard
  annotations:
    iam.gke.io/gcp-service-account: pulseguard-gateway@project-73d1e32a-8e68-4750-93c.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ml-inference
  namespace: pulseguard
  annotations:
    iam.gke.io/gcp-service-account: pulseguard-ml@project-73d1e32a-8e68-4750-93c.iam.gserviceaccount.com

