/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StaffLoadRouteImport } from './routes/staff-load'
import { Route as SimulatorRouteImport } from './routes/simulator'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RiskTrendsRouteImport } from './routes/risk-trends'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as InterventionPlannerRouteImport } from './routes/intervention-planner'
import { Route as GeneratorRouteImport } from './routes/generator'
import { Route as ForecastReportRouteImport } from './routes/forecast-report'
import { Route as ForecastRouteImport } from './routes/forecast'
import { Route as ExamplesRouteImport } from './routes/examples'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as IndexRouteImport } from './routes/index'

const StaffLoadRoute = StaffLoadRouteImport.update({
  id: '/staff-load',
  path: '/staff-load',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulatorRoute = SimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskTrendsRoute = RiskTrendsRouteImport.update({
  id: '/risk-trends',
  path: '/risk-trends',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const InterventionPlannerRoute = InterventionPlannerRouteImport.update({
  id: '/intervention-planner',
  path: '/intervention-planner',
  getParentRoute: () => rootRouteImport,
} as any)
const GeneratorRoute = GeneratorRouteImport.update({
  id: '/generator',
  path: '/generator',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastReportRoute = ForecastReportRouteImport.update({
  id: '/forecast-report',
  path: '/forecast-report',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastRoute = ForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesRoute = ExamplesRouteImport.update({
  id: '/examples',
  path: '/examples',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/examples': typeof ExamplesRoute
  '/forecast': typeof ForecastRoute
  '/forecast-report': typeof ForecastReportRoute
  '/generator': typeof GeneratorRoute
  '/intervention-planner': typeof InterventionPlannerRoute
  '/reports': typeof ReportsRoute
  '/risk-trends': typeof RiskTrendsRoute
  '/settings': typeof SettingsRoute
  '/simulator': typeof SimulatorRoute
  '/staff-load': typeof StaffLoadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/examples': typeof ExamplesRoute
  '/forecast': typeof ForecastRoute
  '/forecast-report': typeof ForecastReportRoute
  '/generator': typeof GeneratorRoute
  '/intervention-planner': typeof InterventionPlannerRoute
  '/reports': typeof ReportsRoute
  '/risk-trends': typeof RiskTrendsRoute
  '/settings': typeof SettingsRoute
  '/simulator': typeof SimulatorRoute
  '/staff-load': typeof StaffLoadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/examples': typeof ExamplesRoute
  '/forecast': typeof ForecastRoute
  '/forecast-report': typeof ForecastReportRoute
  '/generator': typeof GeneratorRoute
  '/intervention-planner': typeof InterventionPlannerRoute
  '/reports': typeof ReportsRoute
  '/risk-trends': typeof RiskTrendsRoute
  '/settings': typeof SettingsRoute
  '/simulator': typeof SimulatorRoute
  '/staff-load': typeof StaffLoadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/examples'
    | '/forecast'
    | '/forecast-report'
    | '/generator'
    | '/intervention-planner'
    | '/reports'
    | '/risk-trends'
    | '/settings'
    | '/simulator'
    | '/staff-load'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/examples'
    | '/forecast'
    | '/forecast-report'
    | '/generator'
    | '/intervention-planner'
    | '/reports'
    | '/risk-trends'
    | '/settings'
    | '/simulator'
    | '/staff-load'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/examples'
    | '/forecast'
    | '/forecast-report'
    | '/generator'
    | '/intervention-planner'
    | '/reports'
    | '/risk-trends'
    | '/settings'
    | '/simulator'
    | '/staff-load'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  ExamplesRoute: typeof ExamplesRoute
  ForecastRoute: typeof ForecastRoute
  ForecastReportRoute: typeof ForecastReportRoute
  GeneratorRoute: typeof GeneratorRoute
  InterventionPlannerRoute: typeof InterventionPlannerRoute
  ReportsRoute: typeof ReportsRoute
  RiskTrendsRoute: typeof RiskTrendsRoute
  SettingsRoute: typeof SettingsRoute
  SimulatorRoute: typeof SimulatorRoute
  StaffLoadRoute: typeof StaffLoadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/staff-load': {
      id: '/staff-load'
      path: '/staff-load'
      fullPath: '/staff-load'
      preLoaderRoute: typeof StaffLoadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulator': {
      id: '/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof SimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk-trends': {
      id: '/risk-trends'
      path: '/risk-trends'
      fullPath: '/risk-trends'
      preLoaderRoute: typeof RiskTrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intervention-planner': {
      id: '/intervention-planner'
      path: '/intervention-planner'
      fullPath: '/intervention-planner'
      preLoaderRoute: typeof InterventionPlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generator': {
      id: '/generator'
      path: '/generator'
      fullPath: '/generator'
      preLoaderRoute: typeof GeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecast-report': {
      id: '/forecast-report'
      path: '/forecast-report'
      fullPath: '/forecast-report'
      preLoaderRoute: typeof ForecastReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecast': {
      id: '/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof ForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples': {
      id: '/examples'
      path: '/examples'
      fullPath: '/examples'
      preLoaderRoute: typeof ExamplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  ExamplesRoute: ExamplesRoute,
  ForecastRoute: ForecastRoute,
  ForecastReportRoute: ForecastReportRoute,
  GeneratorRoute: GeneratorRoute,
  InterventionPlannerRoute: InterventionPlannerRoute,
  ReportsRoute: ReportsRoute,
  RiskTrendsRoute: RiskTrendsRoute,
  SettingsRoute: SettingsRoute,
  SimulatorRoute: SimulatorRoute,
  StaffLoadRoute: StaffLoadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
